laurel_sprout: power: switch from tidy_flags to tidy_checks_as_errors
error: device/xiaomi/laurel_sprout/power-libperfmgr/libperfmgr/Android.bp:47:1: module "libperfmgr" variant "android_arm64_armv8-a_static": tidy_flags: should not contain '-warnings-as-errors=android-*,clang-analyzer-security*,cert-*'; use tidy_checks_as_errors instead.